version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=TodoList
  dotnetapi:
    depends_on:
      - db
    build: "./TodoApi"
    ports:
      - "7000:80"
    environment:
      DB_CONNECTION_STRING: "Host=db;Port=5432;Database=TodoList;Username=postgres;Password=password"
